Added Dialogue System
UD-Game-Development-Club/GameOff2024 pull request #28
Opened 2024-11-17 05:40 UTC by Azimura

To Use: Add Dialog Prefab to UI canvas

2024-11-17 19:12 UTC, zoogies commented
@Azimura is this ready for review?

2024-11-17 21:20 UTC, Azimura commented
@zoogies Yes it is

2024-11-17 21:33 UTC, zoogies requested changes
Good work overall, some feedback:
- Use @Daniel-Frederick 's `IInteractible` for item triggered dialog
- Create a prefab we can use to trigger dialog by the player touching a trigger collider

2024-11-17 21:33 UTC, zoogies commented on game/Assets/Scripts/DialogueTrigger.cs
> +        if (input.GetInteractClick() && playerInRange)
should be
```cs
gameInput.GetItemInteraction()
```

2024-11-17 21:33 UTC, zoogies commented on game/Assets/Scripts/DialogueTrigger.cs
> +    }
I would like to have dialog triggers which just by the player walking into them initiate some dialog, but for this specific use case it would be better to trigger the dialog through an interaction (see #25)

2024-11-17 21:33 UTC, zoogies commented on game/Assets/Scripts/DialogueTrigger.cs
> +    }
Since there is already support for player being in range to interact with something via raycast, and its modular by attaching an `IInteractible` component we should use that for any item triggered dialog

2024-11-17 21:34 UTC, zoogies commented
@Daniel-Frederick let me know what you think as well

2024-11-17 21:55 UTC, Azimura commented
> Good work overall, some feedback:
> 
>     * Use @Daniel-Frederick 's `IInteractible` for item triggered dialog
> 
>     * Create a prefab we can use to trigger dialog by the player touching a trigger collider

Updated it so it uses @Daniel-Frederick item interaction.

Unsure of what you mean by "Create a prefab we can use to trigger dialog by the player touching a trigger collider". Do you want the dialog to trigger the moment the player touches the trigger?

2024-11-17 21:56 UTC, Azimura commented on game/Assets/Scripts/DialogueTrigger.cs
> +        if (input.GetInteractClick() && playerInRange)
Removed entirely after integration with item interaction

2024-11-17 22:10 UTC, Azimura commented on game/Assets/Scripts/DialogueTrigger.cs
> +    }
Updated block:

- Removed OnTriggerExit
- Modify OnTriggerEnter to auto start dialogue

2024-11-17 22:25 UTC, Daniel-Frederick commented on game/Assets/Scripts/Dialogue.cs
> +    }
When making getters and setters in C# you should just use the shorthanded version:
public GameObject DialogueText { get; set; }
public GameObject DialogueChoicePanel { get; set; }

In this case you only need a getter so you could even do this:
public GameObject DialogueText => dialogueText;
public GameObject DialogueChoicePanel => dialogueChoicePanel;

Also there is really no point in making a setter private since the point of getters and setters is for OTHER classes to access the variable. These methods must be public so the other classes can access it. If you don't need a setter, then don't make it. I would ask ChatGPT about the shorthanded versions of getters and setters in C#.

2024-11-17 22:31 UTC, Azimura commented on game/Assets/Scripts/Dialogue.cs
> +    }
Made the changes specified above to Dialogue.cs

2024-11-17 23:23 UTC, Daniel-Frederick commented
I am not sure what we want in DialogueTrigger.cs. You can Trigger the dialogue by colliding or interacting with an object with the 'F' Key. Not sure what we want so I will leave that to @zoogies to decide. We could split the interactions if needed. 
For example: When entering a new area, you collide with an invisible object that will trigger the dialogue. If we add NPCs we could make another script that makes it so you can interact with the NPC but does not trigger when you collide. 
Other than that LGTM

2024-11-17 23:28 UTC, zoogies commented
IMO it should be two separate possibilities:
- object is marked as intractable and implements a dialog function call in its `OnInteraction()`
- we can trigger the `OnTriggerEnter()` for an invisible collider to start dialog

Those two should cover any use case I can think of, for this game at least.

2024-11-17 23:33 UTC, Daniel-Frederick commented
@Azimura  To help you out, the Interact() function in the interface already has the functionality of a OnInteraction() method. You should just rename Interact() to OnInteraction(). Rename it everywhere in the code, hope this helped :)

2024-11-18 05:12 UTC, Azimura commented
> @Azimura To help you out, the Interact() function in the interface already has the functionality of a OnInteraction() method. You should just rename Interact() to OnInteraction(). Rename it everywhere in the code, hope this helped :)

I have updated this.

2024-11-18 18:19 UTC, zoogies approved these changes
LGTM! Good work!

2024-11-18 18:19 UTC, zoogies commented
@Daniel-Frederick since this is a large PR I would like you to give it one more look over before we merge, but this looks good to me

2024-11-19 00:29 UTC, Daniel-Frederick approved these changes
LGTM

2024-11-19 00:29 UTC, merged