The working Pick up controller
UD-Game-Development-Club/GameOff2024 pull request #31
Opened 2024-11-19 23:46 UTC by Daniel-Frederick

Interact/Pick up: F
Drop Object: R
Throw: Left Mouse

2024-11-19 23:56 UTC, zoogies commented
To me drop would make more sense on something like G, but thats really just a nitpick

2024-11-19 23:58 UTC, Daniel-Frederick commented
I could change that in 5 seconds if needed

2024-11-19 23:59 UTC, zoogies requested changes
Overall it looks good, nice work!!!! Let me know your thoughts on these comments though and then we can merge depending

2024-11-19 23:59 UTC, zoogies commented on game/Assets/Scripts/Outliner.cs
> +
Maybe remove if unused

2024-11-19 23:59 UTC, zoogies commented on game/Assets/Scripts/Outliner.cs
> +        Debug.DrawRay(playerCamera.transform.position, playerCamera.transform.forward * interactor.InteractRange, Color.red);
Should this be commented out for prod?

2024-11-20 00:01 UTC, zoogies commented
G has been my experience by default for many games, but I say we just leave it on R

2024-11-20 00:01 UTC, Daniel-Frederick commented
> to nitpick more g is a bad drop button and makes you extend your finger too far

I agree

@zoogies I will remove those for sure, thanks

2024-11-20 00:02 UTC, Cavekitty16 commented
I love how easily persuaded yall are

2024-11-20 00:10 UTC, zoogies approved these changes
LGTM, thanks

2024-11-20 00:10 UTC, merged