Implementing House Puzzles & Dialogue changes
UD-Game-Development-Club/GameOff2024 pull request #48
Opened 2024-11-28 04:51 UTC by Cavekitty16

2024-11-28 04:56 UTC, Cavekitty16 commented
Please Dont Merge Yet, abandoned House has merging conflicts

2024-11-28 05:03 UTC, Cavekitty16 commented
Paintings play sound on awake when adding sound source with script

2024-11-29 02:09 UTC, zoogies commented on game/Assets/Scripts/Abandoned House Puzzles/Paintings/PaintingLights.cs
lol

2024-11-30 17:38 UTC, zoogies requested changes

2024-11-30 17:38 UTC, zoogies commented on game/Assets/Scripts/OutroCutsceneController.cs
What was the purpose of these changes? I just tweaked this scene in main more or less to the same effect so it will conflict with this

2024-11-30 17:38 UTC, zoogies commented on game/Assets/Scripts/Abandoned House Puzzles/Paintings/PaintingLights.cs
This causes a runtime error btw, needs to be resolved/removed

2024-11-30 19:52 UTC, zoogies approved these changes
LGTM

2024-11-30 19:52 UTC, merged